### ISSUE TITLE
Host inventored without licenses especially MS Office licenses

### ISSUE THREAD

**Issue by linuxma** [tabad/fusioninventory-agent-windows-installer#10] opened 2015-10-14 18:01 UTC
Hello,

I have fusioninventory-agent_windows-x64_2.3.17 installed on windows 10 professional 64 bits ! The only issue right now that no license in glpi despite they are inventoried by the agent !

Thanks !

**Comment by g-bougard** [comment] 2015-10-15 10:07
Hi linuxma, first, I would advise you to not include this long output in the issue for 2 reasons: too long and you're publicly exposing your office licenses... I think these keys should be kept totally private...

After that, you're just saying the agent is doing it job. So this is not an issue here. The problem is mostly a GLPI or FusionInventory for GLPI problem which doesn't show the license.

So please try to check or even update your GLPI installation (GLPI v0.90 was released last thursday). Close this issue. And after that if you still have an issue, open another one related to [fusioninventory-for-glpi](https://github.com/fusioninventory/fusioninventory-for-glpi).

Thanks

**Comment by linuxma** [comment] 2015-10-16 01:04
Thanks for the advice !

For GLPI, I tried enough versions ! At this moment, I'm using the last version - 0.90 - with the last FusionInventory for GLPI from github and there is no licenses inserted into MySQL to be displayed !

My best regards.

**Closed** 2015-11-03 17:59 UTC
